### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Exit#1]
Can someone update the readme so @osgyan knows what to put where.
I found some doubles?
al-lock in /usr/bin , also in /etc/skel/.config/archlabs/al-lock and ~/.config/archlabs/al-lock
we need to sort out what goes where in order to make it work.

**Comment by Dobbie03** [comment]
No doubles.  What I put there is correct.

**Comment by erikdubois** [comment]
ok closing
